name: Lint and Test

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install flake8 pytest numpy tensorflow
          pip install fastjet 

      - name: Debug Logs
        run: |
          python -c "import fastjet"
          echo "fastjet version: $(python -c 'import fastjet; print(fastjet.__version__)')"

      - name: Run tests and linting
        run: |
          flake8 .
          pytest
