name: Lint and Test

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install flake8 pytest numpy tensorflow
          pip install fastjet  # If fastjet is available through pip
          # Additional setup for fastjet if needed

      - name: Run flake8
        run: |
          flake8 . --count --show-source --statistics --max-line-length=88 --extend-ignore=E203,W503

      - name: Run pytest
        run: pytest
